"""
Django settings for hotel_saas project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s&7h5!l0g_kmlyvvc4$_tgl2=l%%@w+b&wq14+!!_y)_y8xhar'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "unfold",                     # ← এটা সবার আগে রাখতে হবে!
    "unfold.contrib.filters",     # optional (যদি advanced filter লাগে)
    "unfold.contrib.forms",       # optional
    "unfold.contrib.inlines",     # optional
    "django.contrib.admin",
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_tailwind_cli',
    'django_htmx',
    'apps.site_settings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'hotel_saas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hotel_saas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# এই লাইনটি যোগ করুন (জ্যাঙ্গোকে স্ট্যাটিক ফোল্ডার চেনানোর জন্য)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Tailwind CLI-কে বলে দিন আপনার input.css কোথায় আছে এবং output কোথায় হবে
TAILWIND_CLI_SRC_CSS = 'static/css/input.css'
TAILWIND_CLI_DIST_CSS = 'css/style.css'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# Unfold settings
# settings.py (শেষের দিকে)
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "Mostafizur Admin",
    "SITE_HEADER": "Mostafizur Panel",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,

    "SIDEBAR": {
        "show_search": True,                    # সাইডবারে সার্চ বক্স দেখাবে
        "show_all_applications": False,         # শুধু custom navigation দেখাবে
        
        "navigation": [
            # --- প্রথম সেকশন (Quick Links) ---
            {
                "title": _("Quick Links"),
                "separator": True,              # উপরে separator line
                "collapsible": True,            # ক্লিক করে collapse করা যাবে
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",            
                        "link": reverse_lazy("admin:index"),  
                        "badge": "new",                 
                        "badge_variant": "info",        
                    },
                ],
            },

            # --- দ্বিতীয় সেকশন (Site Settings ডিভাইডার হিসেবে কাজ করবে) ---
            {
                "title": _("Site Settings"),    # এটি মেনুর মাঝখানে হেডিং হিসেবে দেখাবে
                "separator": True,              # এটি হেডিংয়ের উপরে সুন্দর একটি দাগ (divider) তৈরি করবে
                "collapsible": True,
                "items": [
                    {
                        "title": _("All Contacts"),
                        "icon": "contact_page",
                        # হার্ডকোডেড লিংকের বদলে reverse_lazy সবচেয়ে সেফ
                        "link": reverse_lazy("admin:site_settings_contact_changelist"),
                    },
                    # আরও আইটেম চাইলে যোগ করতে পারেন, যেমন:
                    # {
                    #     "title": _("Site Config"),
                    #     "icon": "settings",
                    #     "link": reverse_lazy("admin:site_settings_siteconfig_changelist"),
                    # },
                ],
            },
        ],
    },

    # Optional: Dark mode
    "DARK_MODE": "auto",  # "auto" → সিস্টেমের উপর ডিপেন্ড করে, অথবা True/False
}