"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s&7h5!l0g_kmlyvvc4$_tgl2=l%%@w+b&wq14+!!_y)_y8xhar'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]  # production-এ এটা ঠিক করো → ['yourdomain.com', '.vercel.app'] ইত্যাদি


# Application definition

INSTALLED_APPS = [
    "unfold",                     # ← এটা সবার আগে রাখতে হবে!
    "unfold.contrib.filters",     # optional (যদি advanced filter লাগে)
    "unfold.contrib.forms",       # optional
    "unfold.contrib.inlines",     # optional
    "django.contrib.admin",
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_tailwind_cli',
    'django_htmx',
    'apps.accounts',
    'apps.site_settings',
    'apps.billing',
    'apps.hotels',
]

AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'apps.billing.middleware.SubscriptionCheckMiddleware',
]

# Static files storage (optional কিন্তু ভালো)
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # list হিসেবে দিলাম (তোমার 'templates' ছিল string)
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# তোমার custom static ফাইলগুলো এখান থেকে নেবে
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Production-এ collectstatic যেখানে সব ফাইল কপি করবে (এটা না থাকলে error আসে)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Optional: production-এ cache-busting + compression (whitenoise install করে ব্যবহার করলে ভালো)
# pip install whitenoise
# STORAGES = {
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
#     },
# }

# django-tailwind-cli settings
# input file: static/css/input.css → BASE_DIR থেকে relative
TAILWIND_CLI_SRC_CSS = 'static/css/input.css'

# output file: static/css/style.css → STATICFILES_DIRS[0] থেকে relative (অর্থাৎ css/style.css হিসেবে collect হবে)
TAILWIND_CLI_DIST_CSS = 'css/style.css'

# Optional: production-এ minified চাইলে
# TAILWIND_CLI_MINIFIED = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py (শেষের দিকে)
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "Mostafizur Admin",
    "SITE_HEADER": "Mostafizur Panel",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,  # False রাখলে শুধু নিচের navigation দেখাবে

        "navigation": [
            {
                "title": _("Quick Links"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                        "badge": "home",
                        "badge_variant": "success",  # primary, success, info, warning, danger
                    },
                    # Optional: যদি কোনো custom admin view থাকে
                    # {
                    #     "title": _("Reports"),
                    #     "icon": "bar_chart",
                    #     "link": "/admin/custom-reports/",  # custom URL
                    # },
                ],
            },

            # Hotel Management
            {
                "title": _("Hotel Management"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("All Hotels"),
                        "icon": "apartment",
                        "link": reverse_lazy("admin:hotels_hotel_changelist"),
                    },
                    # যদি আরও মডেল থাকে hotels অ্যাপে (যেমন Room, Review)
                    # {
                    #     "title": _("Rooms"),
                    #     "icon": "meeting_room",
                    #     "link": reverse_lazy("admin:hotels_room_changelist"),
                    # },
                ],
            },

            # Site Settings (Contact + অন্যান্য যদি থাকে)
            {
                "title": _("Site Settings"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Contact Messages"),
                        "icon": "contact_mail",
                        "link": reverse_lazy("admin:site_settings_contact_changelist"),
                    },
                    # যদি আরও কিছু মডেল থাকে site_settings-এ (যেমন FAQ, Setting)
                    # {
                    #     "title": _("General Settings"),
                    #     "icon": "settings",
                    #     "link": reverse_lazy("admin:site_settings_setting_changelist"),
                    # },
                ],
            },

            # Billing & Subscriptions (ইতিমধ্যে আছে, আরও যোগ করতে পারো)
            {
                "title": _("Billing & Subscriptions"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Plans"),
                        "icon": "sell",
                        "link": reverse_lazy("admin:billing_plan_changelist"),
                    },
                    {
                        "title": _("Subscriptions"),
                        "icon": "card_membership",
                        "link": reverse_lazy("admin:billing_subscription_changelist"),
                    },
                    # Optional
                    # {
                    #     "title": _("Payments"),
                    #     "icon": "payments",
                    #     "link": reverse_lazy("admin:billing_payment_changelist"),
                    # },
                ],
            },

            # User Accounts
            {
                "title": _("User Accounts"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "group",
                        "link": reverse_lazy("admin:accounts_user_changelist"),
                    },
                ],
            },

            # Optional: শেষে Logs / History / অন্যান্য
            {
                "title": _("System"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Recent Actions"),
                        "icon": "history",
                        "link": lambda request: reverse_lazy("admin:index") + "#history",
                    },
                ],
            },
        ],
    },

    "DARK_MODE": "auto",
}