# Generated by Django 5.2.1 on 2026-02-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(max_length=20, unique=True, verbose_name='Hotel ID (e.g., BD-DHA-00001)')),
                ('name', models.CharField(max_length=255, verbose_name='Hotel Name')),
                ('hotel_type', models.CharField(blank=True, max_length=100, verbose_name='Hotel Type')),
                ('division', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('upazila_thana', models.CharField(max_length=100, verbose_name='Upozila/Thana')),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('manager_owner_name', models.CharField(blank=True, max_length=255, verbose_name='Manager/Owner Name')),
                ('manager_phone', models.CharField(blank=True, max_length=20, verbose_name='Manager/Owner Phone')),
                ('primary_phone', models.CharField(max_length=20)),
                ('secondary_phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook', models.URLField(blank=True)),
                ('google_maps_link', models.URLField(blank=True, verbose_name='Google Maps Link')),
                ('website', models.URLField(blank=True)),
                ('other_link', models.URLField(blank=True, verbose_name='Other Link')),
                ('rent_range', models.CharField(blank=True, max_length=100, verbose_name='Rent Range (TK)')),
                ('rent_category', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('star_rating', models.CharField(blank=True, max_length=50, verbose_name='Star Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotels',
                'ordering': ['name'],
            },
        ),
    ]
