# Generated by Django 5.2.1 on 2026-02-26 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BD_District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_bn', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'BD Districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BD_Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_bn', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'BD Divisions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BD_Upazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_bn', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'BD Upazilas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hospitality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitality_id', models.CharField(max_length=20, unique=True, verbose_name='ID (e.g., BD-DHA-00001)')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('manager_owner_name', models.CharField(blank=True, max_length=255, verbose_name='Manager/Owner Name')),
                ('manager_phone', models.CharField(blank=True, max_length=20)),
                ('primary_phone', models.CharField(max_length=20)),
                ('secondary_phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook', models.URLField(blank=True)),
                ('google_maps_link', models.URLField(blank=True, verbose_name='Google Maps Link')),
                ('website', models.URLField(blank=True)),
                ('other_link', models.URLField(blank=True, verbose_name='Other Link')),
                ('rent_range', models.CharField(blank=True, max_length=100, verbose_name='Rent Range (TK)')),
                ('rent_category', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('star_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Star Rating (e.g. 4.5)')),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, editable=False, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0, editable=False)),
                ('hotel_type', models.CharField(blank=True, max_length=100, verbose_name='Type (Hotel/Resort/Guest House etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hospitalities',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.AddField(
            model_name='bd_district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='site_settings.bd_division'),
        ),
        migrations.AddField(
            model_name='bd_upazila',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upazilas', to='site_settings.bd_district'),
        ),
        migrations.AddField(
            model_name='hospitality',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalities', to='site_settings.bd_district'),
        ),
        migrations.AddField(
            model_name='hospitality',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalities', to='site_settings.bd_division'),
        ),
        migrations.AddField(
            model_name='hospitality',
            name='upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalities', to='site_settings.bd_upazila', verbose_name='Upozila/Thana'),
        ),
        migrations.AlterUniqueTogether(
            name='bd_district',
            unique_together={('division', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='bd_upazila',
            unique_together={('district', 'name')},
        ),
    ]
