# Generated by Django 5.2.1 on 2026-02-26 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_bd_district_bd_division_bd_upazila_hospitality_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bd_upazila',
            unique_together=set(),
        ),
    ]
